services:
  ollama-gpu:
    image: dockerhub.timeweb.cloud/ollama/ollama:rocm
    # Указываем короткое имя для команд терминала
    container_name: ollama-gpu
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    security_opt:
      - seccomp=unconfined
    volumes:
      - /opt/ollama/models:/root/.ollama/models   
    ports:
      - "11434:11434"
    environment:
      - HSA_OVERRIDE_GFX_VERSION=12.0.0
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
      - OLLAMA_MAX_LOADED_MODELS=1       # только одна модель в памяти
      - OLLAMA_NUM_PARALLEL=1            # один запрос за раз (экономия памяти)
      - OLLAMA_KEEP_ALIVE=30m            # держать модель 30 минут после последнего запроса
      - OLLAMA_CONTEXT_LENGTH=32768
    restart: unless-stopped
    scale: 1  # Создаст 0 копий этого контейнера (пропустит запуск)

  comfyui-gpu:
    image: dockerhub.timeweb.cloud/yanwk/comfyui-boot:rocm
    container_name: comfyui
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    security_opt:
      - seccomp=unconfined
    volumes:
      - /opt/comfyui/root:/root
      - /home/kirgizov/_projects/comfyui/comfyui-kela-ollama:/root/ComfyUI/custom_nodes/comfyui-kela-ollama
      - /opt/rocm:/opt/rocm:ro
    ports:
      - "8188:8188"
    environment:
      - HSA_OVERRIDE_GFX_VERSION=12.0.0
    restart: unless-stopped
    scale: 1  # Создаст 0 копий этого контейнера (пропустит запуск)
